version: "3"
services:
  db:
    container_name: mariadb
    image: mariadb
    restart: unless-stopped
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: GvJS8ZLMvRZtiUGMQB2D
      MYSQL_PASSWORD: 68yqU1eqg0JfvFTO
      MYSQL_DATABASE: todo
      MYSQL_USER: todo

  frontend_react:
    container_name: frontend
    restart: unless-stopped
    build:
      context: ./todo_frontend
      dockerfile: ./Dockerfile
      args:
        environment: dev
        status: stable
    ports:
      - 3080:80

  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: ./simpletodo_backend
      dockerfile: ./Dockerfile
      args:
        environment: dev
        status: stable
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db